import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import CategoryHero from "../components/CategoryHero.jsx";

function health() {
  const content = [
    {
      title: "Health",
      content1: `Maintaining a high level of physical health is crucial for optimal mental well-being. When our bodies are functioning at their best, our minds are better equipped to handle the challenges of daily life. Conversely, when we neglect our physical health, it can take a toll on our mental state. Poor nutrition, lack of sleep, and inactivity can all contribute to feelings of depression, anxiety, and general malaise. On the other hand, a healthy diet, regular exercise, and sufficient rest can work wonders for our mental clarity, energy levels, and overall happiness.`
    }
  ];

  return (
    <>
      <Head>
        <title>MMH | Health</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CategoryHero title={content[0].title} content1={content[0].content1} />
    </>
  );
}

export default health;
