import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Header from "../components/Header.jsx"
import Pillars from "../components/Pillars"
import SignUp from "../components/SignUp"
import { Sign } from "crypto";
import WhatsIncluded from "../components/WhatsIncluded.jsx"
import Footer from "../components/Footer"
import NavbarNew from "../components/NavbarNew";


const inter = Inter({ subsets: ["latin"] });

export default function Home() {


  return (
    <main className="bg-gray-800">
      <Head>
        <title>MMH</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavbarNew />
      <Header />
      <Pillars />
      <SignUp />
      <WhatsIncluded />
      <Footer />
    </main>
  );
}
