import { useState } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import CategoryHero from "../components/CategoryHero.jsx";

function relationship() {
  const content = [
    {
      title: "Relationship",
      content1: `The power of friendship and close relationships should not be underestimated when it comes to maintaining positive mental health. In fact, research has shown that having strong social connections is one of the most important factors in overall well-being. Friends and loved ones provide us with a sense of belonging, support, and unconditional love, all of which are essential for our mental and emotional well-being. They may just be the key to maintaining a positive state of mind.`
    }
  ];

  return (
    <>
      <Head>
        <title>MMH | Relationships</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CategoryHero title={content[0].title} content1={content[0].content1} />
    </>
  );
}

export default relationship;
